name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-python-app:latest .

      # Test Docker image health endpoint
      - name: Test Docker image
        run: |
          docker run -d -p 5000:5000 --name test-app \
            -e DB_USER=testuser \
            -e DB_PASSWORD=testpass \
            my-python-app:latest
          sleep 5
          curl --retry 3 --retry-delay 5 http://localhost:5000/health
          docker stop test-app
          docker rm test-app
